### ISSUE TITLE
Rough Project Plan

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/basecoin-rs#1]
# Goal

Objective: Fully complete IBC handlers in rust that can easily be integrated into any Rust blockchain framework, including Orga, Penumbra, Anoma, Substrate, Near, Solana, etc. 

Major Milestone:  simple ABCI app ("basecoin") that supports IBC token transfer. We want to be able to run two instances of this chain and use hermes to transfer tokens between them.

Future major milestones include having our IBC handlers connect to the Cosmos Hub, having a more robust "baseapp" framework (whether Orga or something else), and integrating smart contracting languages like CosmWasm or even [Makina](https://github.com/informalsystems/tla-sharp) 

# Draft Plan

Here's a draft plan broken into phases.

Phases 0-2: simplest ABCI app possible to be able to support IBC

- [x] Phase 0: dummy basecoin
    - in memory state map: account address (string) -> balance (int)
    - single tx type json encoded with three fields: sender, receiver, amount

- [x] Phase 1: Same as Phase 0 but with protobuf based txs using Cosmos SDK Tx structure
    - use the Cosmos-SDK tx/v1beta1/tx.proto `message Tx`, but ignore all auth/signatures (just get the Msg out)
    - use the bank/v1beta1/tx.proto MsgSend to get the from/to/amount
    - use the same in memory state map as Phase 0
    - should be able to use `gaiad tx bank send --offline whatever` to send txs

- [x] Phase 2: Add support for multiple coins
    - state map is now `map [  address (string) -> map[ denom (string) -> amount (int) ]  ]`
    - everything else should be the same !
------

Phases 3-6: IBC integration into the ABCI app

- [x] Phase 3: Add support for IBC CreateClient and UpdateClient msgs
    - complete/import the ics02/ics07 machinery from ibc-rs
    - state will now need to be able to store clients (may need more generic state mechanism ? )
    - allow sending MsgCreateClient to create client on the chain and MsgUpdateClient to update it with latest headers
    - should be able to use `hermes tx raw create/update-client` and/or `gaiad tx ibc ...`
    - should be able to run two chains, manually create a client on each, and manually update them

NOTE: at some point we need to add GRPC support to get hermes working properly and not have to do commands manually - probably should do this sooner than later.

- [x] Phase 4: Add support for IBC Connection machinery
    - complete/import the ics03 machinery from ibc-rs
    - state will now need to be able to store connection ends
    - should now be able to manually complete connection handshake between two chains

- [x] Phase 5: Add support IBC Channel machinery
    - complete/import the ics04 machinery from ibc-rs
    - state will now need to be able to store channel ends and packet data
    - should now be able to manually complete channel handshakes between two chains and send packets

- [ ] Phase 6: Add support for IBC Token Transfer
    - complete/import the ics20 machinery from ibc-rs
    - should now be able to transfer tokens from one chain to the other

TADA! 

------

- [ ] Phase 7: Get it working with the Cosmos Hub ....

- [ ] Phase 8: use a real app framework and make everything secure ... 

OPEN QUESTION:
- what parts of ibc-rs are still incomplete and need to be filled in to get this working? 
- are there parts we can still punt on ? eg. merkle tree verification
- what do we need the state to look like to make this work ? 
- what do we need to expose to enable hermes to run against these two chains and do everything automatically (ie. grpc ? )

**Comment by DaviRain-Su** [comment]
I recently discovered bascoin-rs, which is implementing a Rust version of the Cosmos SDK. It's absolutely amazing!

**Comment by plafer** [comment]
The project has turned more recently into a chain that uses ibc-rs, to give us better insights into how using the ibc-rs API feels, as well as run some integration tests before every release of ibc-rs. Unfortunately it is not on the roadmap to make a "Rust Cosmos SDK" of it

**Comment by DaviRain-Su** [comment]
> Unfortunately it is not on the roadmap to make a "Rust Cosmos SDK" of it
I understand what you mean, but I'm really interested in using Rust to implement the Cosmos SDK.

**Comment by DaviRain-Su** [comment]
First Step : https://github.com/informalsystems/basecoin-rs/pull/110
